INSERT INTO `#__jcomments_settings` VALUES 
('', '', 'enable_username_check', '1'),
('', '', 'username_maxlength', '20'),
('', '', 'forbidden_names', 'administrator,moderator'),
('', '', 'author_name', '2'),
('', '', 'author_email', '2'),
('', '', 'author_homepage', '1'), 
('', '', 'comment_maxlength', '1000'),
('', '', 'comment_minlength', '0'),
('', '', 'word_maxlength', '50'),
('', '', 'link_maxlength', '50'),
('', '', 'flood_time', '30'),
('', '', 'enable_notification', '0'),
('', '', 'notification_email', ''),
('', '', 'template', 'default'),
('', '', 'template_view', 'list'),
('', '', 'enable_smilies', '1'),
('', '', 'comments_per_page', '10'),
('', '', 'comments_page_limit', '15'),
('', '', 'comments_pagination', 'both'),
('', '', 'comments_list_order', 'DESC'),
('', '', 'comments_tree_order', '0'),
('', '', 'show_commentlength', '1'),
('', '', 'enable_nested_quotes', '1'),
('', '', 'enable_rss', '1'),
('', '', 'censor_replace_word', '[censored]'),
('', '', 'show_policy', 'Public,Registered'),
('', '', 'enable_captcha', 'Public'),
('', '', 'floodprotection', 'Public,Registered,Author,Editor'),
('', '', 'enable_comment_length_check', 'Public,Registered'),
('', '', 'autopublish', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'autolinkurls', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_subscribe', 'Public,Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_gravatar', ''),
('', '', 'can_comment', 'Public,Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'can_reply', 'Public,Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'can_view_homepage', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'can_publish', 'Publisher,Manager,Administrator,Super Users'),
('', '', 'can_publish_for_my_object', ''),
('', '', 'can_view_email', 'Manager,Administrator,Super Users'),
('', '', 'can_edit', 'Manager,Administrator,Super Users'),
('', '', 'can_edit_own', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'can_edit_for_my_object', ''),
('', '', 'can_delete', 'Manager,Administrator,Super Users'),
('', '', 'can_delete_own', 'Manager,Administrator,Super Users'),
('', '', 'can_delete_for_my_object', ''),
('', '', 'can_report', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'can_ban', 'Administrator,Super Users'),
('', '', 'can_vote', 'Public,Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'can_view_ip', 'Administrator,Super Users'),
('', '', 'enable_bbcode_b', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_bbcode_i', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_bbcode_u', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_bbcode_s', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_bbcode_url', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_bbcode_img', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_bbcode_list', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_bbcode_hide', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_bbcode_quote', 'Public,Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_bbcode_code', 'Registered,Author,Editor,Publisher,Manager,Administrator,Super Users'),
('', '', 'enable_categories', ''),
('', '', 'emailprotection', 'Public'),
('', '', 'enable_comment_maxlength_check', ''),
('', '', 'enable_autocensor', 'Public'),
('', '', 'badwords', ''),
('', '', 'smilies', ':D	laugh.gif\n:lol:	lol.gif\n:-)	smile.gif\n;-)	wink.gif\n8)	cool.gif\n:-|	normal.gif\n:-*	whistling.gif\n:oops:	redface.gif\n:sad:	sad.gif\n:cry:	cry.gif\n:o	surprised.gif\n:-?	confused.gif\n:-x	sick.gif\n:eek:	shocked.gif\n:zzz	sleeping.gif\n:P	tongue.gif\n:roll:	rolleyes.gif\n:sigh:	unsure.gif'),
('', '', 'enable_plugins', '1'),
('', '', 'form_show', '1'),
('', '', 'display_author', 'name'),
('', '', 'enable_voting', '1'),
('', '', 'merge_time', '0'),
('', '', 'message_policy_post', ''),
('', '', 'message_policy_whocancomment', 'You have no rights to post comments'),
('', '', 'message_locked', 'Comments are now closed for this entry'),
('', '', 'comment_title', '0'),
('', '', 'enable_custom_bbcode', '0'),
('', '', 'enable_geshi', '0'),
('', '', 'enable_quick_moderation', '0'),
('', '', 'notification_type', '1,2'),
('', '', 'delete_mode', '0'),
('', '', 'enable_blacklist', '0'),
('', '', 'smilies_path', '/components/com_jcomments/images/smilies/'),
('', '', 'feed_limit', '100'),
('', '', 'report_reason_required', '1')
;
